services:
  # Backend API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: wedding-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://localhost
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECURE_COOKIES=${SECURE_COOKIES:-false}
    volumes:
      - wedding-data:/app/data
    ports:
      - "3001:3001"
    networks:
      - wedding-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Astro Server
  ui-server:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: wedding-ui-server
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    networks:
      - wedding-network
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Proxy
  ui:
    image: nginx:alpine
    container_name: wedding-ui-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./ui/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - wedding-network
    depends_on:
      - ui-server
      - api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Reverse Proxy (opcional, para producción avanzada)
  nginx-proxy:
    image: nginx:alpine
    container_name: wedding-proxy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - wedding-network
    depends_on:
      - ui
      - api
    profiles:
      - production

networks:
  wedding-network:
    driver: bridge

volumes:
  wedding-data:
    driver: local