# Configuración para desarrollo local
services:
  # Backend API en modo desarrollo
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: wedding-api-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=${FRONTEND_URL}
      - API_URL=${API_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECURE_COOKIES=${SECURE_COOKIES}
      - CORS_ORIGIN=${CORS_ORIGIN}
    volumes:
      - ./api:/app
      - /app/node_modules
      - ./api/wedding.db:/app/wedding.db
    ports:
      - "3001:3001"
    networks:
      - wedding-network
    command: npm run dev

  # Frontend UI en modo desarrollo
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: wedding-ui-dev
    restart: unless-stopped
    environment:
      - API_URL=http://localhost:3001
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    networks:
      - wedding-network
    depends_on:
      - api
    command: npm run dev -- --host 0.0.0.0

networks:
  wedding-network:
    driver: bridge